version: '3'

services:
  uello-app:
    container_name: uello-app
    hostname: uello-app
    working_dir: /usr/share/nginx
    image: wyveo/nginx-php-fpm:latest
    ports:
      - "8080:80"
    depends_on:
      - uello-mysql-app
    volumes:
      - ./:/usr/share/nginx
      - ./infra/nginx:/etc/nginx/conf.d/
    networks:
      - app-network

  uello-mysql-app:
    container_name: uello-mysql-app
    image: mysql:5.7.37
    ports:
      - "3306:3306"
    volumes:
       - ./docker/dbdata:/docker-entrypoint-initdb.d
       - ./docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
